name: update-description

on:
  push:
    branches: master
    paths:
      - "README.md"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_REPOSITORY: ptst/digitalocean-dyndns
