name: update-description

on:
  push:
    branches: master
    paths:
      - "README.md"
      - .github/workflows/update-description.yml

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2.3.1
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: ptst/digitalocean-dyndns
